---
replicaCount: 1
image_pullPolicy: IfNotPresent
image_tag: latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount_create: true
serviceAccount_annotations: {}
serviceAccount_name: ""
service_type: ClusterIP
service_port: 5000
ingress_enabled: true
ingress_className: ""
ingress_host: flask-dev.209.38.176.143.nip.io
ingress_paths:
  - path: /tasks
    pathType: Prefix
ingress_tls: []
autoscaling_enabled: false
argocd_app_destination_server: https://kubernetes.default.svc
argocd_app_destination_server: https://kubernetes.default.svc
