

replicaCount: 1

image:
  repository: eon0x1/cicd-flask-docker
  pullPolicy: IfNotPresent
  tag: "latest"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: True
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: True
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: flask-staging.209.38.176.143.nip.io
      paths:
        - path: /tasks
          pathType: Prefix

